insert into Rating (id, review, score, user_id, product_id) values (1, 'Hearty chili made with beans and vegetables, a savory meal option.', 30, 380, 506);
insert into Rating (id, review, score, user_id, product_id) values (2, 'A light and tangy dressing with poppy seeds, perfect for salads.', 52, 311, 477);
insert into Rating (id, review, score, user_id, product_id) values (3, 'A nutritious salad with kale, quinoa, and a zesty lemon dressing.', 18, 448, 1122);
insert into Rating (id, review, score, user_id, product_id) values (4, 'Durable speaker designed for outdoor use with water resistance.', 59, 655, 761);
insert into Rating (id, review, score, user_id, product_id) values (5, 'Creamy honey mustard sauce for dipping or dressing.', 44, 145, 1931);
insert into Rating (id, review, score, user_id, product_id) values (6, 'Set of unique wooden coasters for drinks and decor.', 57, 728, 264);
insert into Rating (id, review, score, user_id, product_id) values (7, 'Chic suede ankle booties, perfect for dressing up or down.', 80, 191, 1818);
insert into Rating (id, review, score, user_id, product_id) values (8, 'Savory sauce for vegetable and meat stir-fries.', 97, 179, 227);
insert into Rating (id, review, score, user_id, product_id) values (9, 'No-bake energy bites made with peanut butter and oats.', 54, 68, 17);
insert into Rating (id, review, score, user_id, product_id) values (10, 'A blend of roasted red peppers and spices, perfect for dipping.', 18, 668, 1298);
insert into Rating (id, review, score, user_id, product_id) values (11, 'Durable backpack for hiking or travel.', 22, 416, 451);
insert into Rating (id, review, score, user_id, product_id) values (12, 'Flavorful mustard with a tangy kick, perfect for hot dogs and sandwiches.', 7, 157, 1626);
insert into Rating (id, review, score, user_id, product_id) values (13, 'Convert your desk to a standing desk easily.', 44, 363, 73);
insert into Rating (id, review, score, user_id, product_id) values (14, 'Durable backpack designed for hiking and outdoor excursions.', 68, 793, 1066);
insert into Rating (id, review, score, user_id, product_id) values (15, 'Refreshing coconut water packed with electrolytes for hydration.', 20, 378, 1428);
insert into Rating (id, review, score, user_id, product_id) values (16, 'Sweet and crunchy roasted almonds.', 93, 357, 833);
insert into Rating (id, review, score, user_id, product_id) values (17, 'Convert your desk to a standing desk easily.', 48, 613, 1860);
insert into Rating (id, review, score, user_id, product_id) values (18, 'Folding massage table for professional or home use.', 51, 450, 1761);
insert into Rating (id, review, score, user_id, product_id) values (19, 'Shredded cabbage and carrots for coleslaw.', 19, 748, 476);
insert into Rating (id, review, score, user_id, product_id) values (20, 'Delicious and tangy marinade for grilling or baking chicken.', 70, 222, 1385);
insert into Rating (id, review, score, user_id, product_id) values (21, 'Battery-operated air purifier for small spaces.', 41, 724, 321);
insert into Rating (id, review, score, user_id, product_id) values (22, 'Ready-to-eat salad with kale, lemon, and cheese.', 56, 459, 390);
insert into Rating (id, review, score, user_id, product_id) values (23, 'Comfortable and warm leggings perfect for colder weather.', 19, 489, 1278);
insert into Rating (id, review, score, user_id, product_id) values (24, 'Variety of bands suitable for all fitness levels.', 32, 134, 1535);
insert into Rating (id, review, score, user_id, product_id) values (25, 'Manual pasta maker for homemade pasta.', 80, 38, 1093);
insert into Rating (id, review, score, user_id, product_id) values (26, 'Crunchy roasted pumpkin seeds, great for snacking.', 79, 480, 297);
insert into Rating (id, review, score, user_id, product_id) values (27, 'Borosilicate glass water bottle with silicone sleeve.', 75, 454, 930);
insert into Rating (id, review, score, user_id, product_id) values (28, 'Set of roller bottles for blending and applying essential oils.', 36, 302, 1046);
insert into Rating (id, review, score, user_id, product_id) values (29, 'Spicy salsa made with fresh ingredients.', 97, 702, 333);
insert into Rating (id, review, score, user_id, product_id) values (30, 'Comfortable over-ear headphones with deep bass.', 42, 182, 1198);
insert into Rating (id, review, score, user_id, product_id) values (31, 'Delicious veggie burgers loaded with grilled vegetables.', 2, 206, 1690);
insert into Rating (id, review, score, user_id, product_id) values (32, 'Set of magnetic jars for convenient spice organization.', 91, 376, 1733);
insert into Rating (id, review, score, user_id, product_id) values (33, 'Hands-on experience with science and engineering projects.', 20, 717, 1034);
insert into Rating (id, review, score, user_id, product_id) values (34, 'Lightly salted frozen edamame, a protein-packed snack.', 29, 195, 66);
insert into Rating (id, review, score, user_id, product_id) values (35, 'Seasoned and roasted to perfection, ready to eat.', 81, 640, 1327);
insert into Rating (id, review, score, user_id, product_id) values (36, 'Easy meal kit for creamy fettuccine Alfredo.', 74, 54, 725);
insert into Rating (id, review, score, user_id, product_id) values (37, 'Delicious cookies packed with oats and raisins.', 14, 114, 1271);
insert into Rating (id, review, score, user_id, product_id) values (38, 'Convenient shower system for camping and outdoor activities.', 55, 389, 1204);
insert into Rating (id, review, score, user_id, product_id) values (39, 'Stylish hooks to easily hang shower curtains.', 46, 446, 1602);
insert into Rating (id, review, score, user_id, product_id) values (40, 'Delicious muffins filled with apples and a hint of cinnamon for breakfast.', 14, 651, 1955);
insert into Rating (id, review, score, user_id, product_id) values (41, 'A spicy, flavorful cheese stick great for snacks or lunchboxes.', 32, 769, 1208);
insert into Rating (id, review, score, user_id, product_id) values (42, 'A nutritious salad with kale, quinoa, and a zesty lemon dressing.', 1, 104, 1653);
insert into Rating (id, review, score, user_id, product_id) values (43, 'Savory, roasted nuts seasoned with garlic and parmesan.', 70, 491, 395);
insert into Rating (id, review, score, user_id, product_id) values (44, 'Love-themed molds for creating desserts and treats.', 19, 76, 1471);
insert into Rating (id, review, score, user_id, product_id) values (45, 'A fitted ribbed knit dress that hugs your curves perfectly.', 88, 673, 750);
insert into Rating (id, review, score, user_id, product_id) values (46, 'Durable tarp for outdoor camping and protection.', 33, 643, 1134);
insert into Rating (id, review, score, user_id, product_id) values (47, 'A classic denim jacket that never goes out of style.', 38, 469, 1020);
insert into Rating (id, review, score, user_id, product_id) values (48, 'Stainless steel measuring spoons set for cooking.', 28, 42, 508);
insert into Rating (id, review, score, user_id, product_id) values (49, 'Ergonomic stand for laptops to improve posture while working.', 13, 429, 1477);
insert into Rating (id, review, score, user_id, product_id) values (50, 'Automatically cooks eggs to your desired level.', 73, 18, 948);
insert into Rating (id, review, score, user_id, product_id) values (51, 'Homemade jam made with blueberries and chia seeds, no added sugar.', 29, 152, 1666);
insert into Rating (id, review, score, user_id, product_id) values (52, 'Educational tablet designed for preschool-age children.', 74, 414, 807);
insert into Rating (id, review, score, user_id, product_id) values (53, 'Instant oatmeal flavored with cranberries and orange zest for breakfast.', 75, 329, 1524);
insert into Rating (id, review, score, user_id, product_id) values (54, 'Complete meal kit with everything needed to make beef stroganoff in under 30 minutes.', 95, 328, 717);
insert into Rating (id, review, score, user_id, product_id) values (55, 'Eco-friendly coffee filter for brewing.', 4, 380, 661);
insert into Rating (id, review, score, user_id, product_id) values (56, 'Portable water bottle for pets when traveling.', 50, 317, 810);
insert into Rating (id, review, score, user_id, product_id) values (57, 'Indoor putting green for practicing your putting skills.', 31, 195, 1711);
insert into Rating (id, review, score, user_id, product_id) values (58, 'Delicious waffles infused with pumpkin and spices.', 25, 353, 1495);
insert into Rating (id, review, score, user_id, product_id) values (59, 'Layers of pasta, veggies, and cheese baked to perfection.', 76, 10, 1290);
insert into Rating (id, review, score, user_id, product_id) values (60, 'Portable case to organize and protect jewelry on trips.', 5, 300, 180);
insert into Rating (id, review, score, user_id, product_id) values (61, 'Fresh kale salad with a zesty lemon dressing, great as a side dish.', 29, 783, 1793);
insert into Rating (id, review, score, user_id, product_id) values (62, 'Spice blend for creating flavorful vegan taco filling.', 49, 538, 422);
insert into Rating (id, review, score, user_id, product_id) values (63, 'Frozen pizza loaded with vegetables and cheese.', 30, 687, 749);
insert into Rating (id, review, score, user_id, product_id) values (64, 'Stylish baskets for organizing various items in your home.', 60, 532, 1372);
insert into Rating (id, review, score, user_id, product_id) values (65, 'Bottle that tracks your water intake and reminds you to drink.', 76, 174, 1395);
insert into Rating (id, review, score, user_id, product_id) values (66, 'Multi-function rice cooker for all types of rice recipes.', 58, 235, 1142);
insert into Rating (id, review, score, user_id, product_id) values (67, 'Pre-seasoned beef mix for delicious tacos, just heat and serve.', 74, 229, 1118);
insert into Rating (id, review, score, user_id, product_id) values (68, 'Retro instant camera for capturing and printing photos instantly.', 47, 701, 1801);
insert into Rating (id, review, score, user_id, product_id) values (69, 'Adjustable shelving unit for home or garage storage.', 19, 541, 566);
insert into Rating (id, review, score, user_id, product_id) values (70, 'High-quality whey protein powder for muscle recovery.', 86, 191, 342);
insert into Rating (id, review, score, user_id, product_id) values (71, 'Convenient stroller for pets to enjoy outdoor walks.', 62, 27, 1114);
insert into Rating (id, review, score, user_id, product_id) values (72, 'Perfect dipping sauce or stir-fry addition for a sweet and tangy flavor.', 88, 593, 122);
insert into Rating (id, review, score, user_id, product_id) values (73, 'Spicy sauce made with chipotle peppers', 49, 103, 210);
insert into Rating (id, review, score, user_id, product_id) values (74, 'Convenient stroller for pets to enjoy outdoor walks.', 27, 628, 456);
insert into Rating (id, review, score, user_id, product_id) values (75, 'Perfectly designed pan for making crepes and pancakes.', 63, 444, 1552);
insert into Rating (id, review, score, user_id, product_id) values (76, 'Easy-to-make falafel mix for a tasty vegetarian meal.', 20, 758, 1151);
insert into Rating (id, review, score, user_id, product_id) values (77, 'Moist and flavorful muffins packed with fall spices and pumpkin puree.', 22, 212, 529);
insert into Rating (id, review, score, user_id, product_id) values (78, 'Soft silicone earbud covers for comfort and fit.', 98, 190, 1040);
insert into Rating (id, review, score, user_id, product_id) values (79, 'Memory foam travel pillow for neck support.', 38, 777, 516);
insert into Rating (id, review, score, user_id, product_id) values (80, 'Multi-angle stand for easy viewing of devices.', 37, 473, 336);
insert into Rating (id, review, score, user_id, product_id) values (81, 'Soft cotton graphic tee available in various designs.', 50, 58, 183);
insert into Rating (id, review, score, user_id, product_id) values (82, 'Frozen smoothie pack with strawberries and bananas.', 29, 105, 1212);
insert into Rating (id, review, score, user_id, product_id) values (83, 'Sweet blackberry compote, perfect for topping desserts.', 66, 284, 1148);
insert into Rating (id, review, score, user_id, product_id) values (84, 'Soft and pillowy gnocchi made from cauliflower, perfect with sauce.', 97, 14, 1533);
insert into Rating (id, review, score, user_id, product_id) values (85, 'Foldable kneeler that doubles as a seat for gardening convenience.', 5, 4, 82);
insert into Rating (id, review, score, user_id, product_id) values (86, 'Sweet and crisp apples, perfect for snacking.', 26, 214, 716);
insert into Rating (id, review, score, user_id, product_id) values (87, 'Frozen smoothie blend with berries for a quick and healthy breakfast.', 41, 408, 1715);
insert into Rating (id, review, score, user_id, product_id) values (88, 'Pure and natural honey, great for sweetening.', 14, 623, 113);
insert into Rating (id, review, score, user_id, product_id) values (89, 'Set of roller bottles for blending and applying essential oils.', 32, 144, 1727);
insert into Rating (id, review, score, user_id, product_id) values (90, 'Fresh and tart organic green apples, great for snacking or baking.', 69, 398, 1078);
insert into Rating (id, review, score, user_id, product_id) values (91, 'Craft your own lip balms with this complete kit.', 84, 476, 147);
insert into Rating (id, review, score, user_id, product_id) values (92, 'Wireless headphones with noise-canceling features.', 83, 710, 1549);
insert into Rating (id, review, score, user_id, product_id) values (93, 'Crunchy cacao nibs, great for adding to smoothies or baking.', 39, 532, 582);
insert into Rating (id, review, score, user_id, product_id) values (94, 'Crisp and sweet Honeycrisp apples, freshly picked.', 24, 146, 946);
insert into Rating (id, review, score, user_id, product_id) values (95, 'The perfect seafood snack, ready to eat and delicious.', 58, 747, 1062);
insert into Rating (id, review, score, user_id, product_id) values (96, 'Fun book filled with puzzles and games for kids.', 15, 408, 1480);
insert into Rating (id, review, score, user_id, product_id) values (97, 'Deliciously creamy almond milk, perfect for smoothies.', 32, 570, 1386);
insert into Rating (id, review, score, user_id, product_id) values (98, 'Assorted nail polish set for vibrant nails.', 72, 479, 1993);
insert into Rating (id, review, score, user_id, product_id) values (99, 'Aromatic fresh basil, perfect for Italian cooking.', 65, 44, 724);
insert into Rating (id, review, score, user_id, product_id) values (100, 'Foldable mat for jigsaw puzzle assembly.', 5, 742, 508);
insert into Rating (id, review, score, user_id, product_id) values (101, 'Creative building set for kids to spark imagination.', 48, 134, 20);
insert into Rating (id, review, score, user_id, product_id) values (102, 'Deliciously smoked salmon, great for bagels.', 95, 178, 28);
insert into Rating (id, review, score, user_id, product_id) values (103, 'Instant miso soup mix, just add hot water for a warm meal.', 46, 163, 1647);
insert into Rating (id, review, score, user_id, product_id) values (104, 'Complete fondue set for chocolate and cheese parties.', 67, 148, 429);
insert into Rating (id, review, score, user_id, product_id) values (105, 'A hearty soup filled with vegetables and herbs, perfect for a light meal.', 81, 28, 1304);
insert into Rating (id, review, score, user_id, product_id) values (106, 'Gentle glove for brushing and massaging your pet.', 78, 788, 51);
insert into Rating (id, review, score, user_id, product_id) values (107, 'Convenient shower system for camping and outdoor activities.', 95, 598, 1644);
insert into Rating (id, review, score, user_id, product_id) values (108, 'Rich and creamy tomato basil soup, perfect with a grilled cheese.', 61, 328, 549);
insert into Rating (id, review, score, user_id, product_id) values (109, 'Rechargeable LED lantern ideal for camping and outdoor activities.', 89, 640, 1673);
insert into Rating (id, review, score, user_id, product_id) values (110, 'Keep bugs out while allowing fresh air in during summer.', 59, 429, 1980);
insert into Rating (id, review, score, user_id, product_id) values (111, 'Hearty chili made with premium ground beef and kidney beans.', 15, 41, 1613);
insert into Rating (id, review, score, user_id, product_id) values (112, 'A nutrient-packed salad mix with kale, quinoa, and a lemon vinaigrette, ready to eat.', 71, 516, 1524);
insert into Rating (id, review, score, user_id, product_id) values (113, 'Complete kit for starting your own organic garden.', 12, 484, 1457);
insert into Rating (id, review, score, user_id, product_id) values (114, 'Stylish cap to complete your athletic look.', 67, 704, 1044);
insert into Rating (id, review, score, user_id, product_id) values (115, 'Just add water for a hearty cheese and broccoli soup in minutes.', 57, 672, 1716);
insert into Rating (id, review, score, user_id, product_id) values (116, 'A fashion-forward bomber jacket to elevate your casual looks.', 22, 532, 654);
insert into Rating (id, review, score, user_id, product_id) values (117, 'Refreshing coconut water packed with electrolytes for hydration.', 86, 64, 369);
insert into Rating (id, review, score, user_id, product_id) values (118, 'Challenging and fun puzzle game for all ages.', 12, 303, 572);
insert into Rating (id, review, score, user_id, product_id) values (119, 'Tangy salsa made from tomatillos and peppers.', 85, 267, 1636);
insert into Rating (id, review, score, user_id, product_id) values (120, 'Ergonomic wireless mouse with adjustable DPI.', 96, 278, 1919);
insert into Rating (id, review, score, user_id, product_id) values (121, 'Creamy Greek yogurt packed with protein and probiotics.', 36, 544, 1983);
insert into Rating (id, review, score, user_id, product_id) values (122, 'Nutritious protein bar with cherry and almond flavor, great for on-the-go.', 29, 15, 129);
insert into Rating (id, review, score, user_id, product_id) values (123, 'Classic chino shorts in a versatile color for summer adventures.', 46, 515, 842);
insert into Rating (id, review, score, user_id, product_id) values (124, 'Assorted herbal tea bags for relaxation and wellness.', 32, 129, 1816);
insert into Rating (id, review, score, user_id, product_id) values (125, 'Elegant glass teapot for brewing loose tea.', 5, 2, 346);
insert into Rating (id, review, score, user_id, product_id) values (126, 'Shredded cabbage and carrots for coleslaw.', 79, 510, 133);
insert into Rating (id, review, score, user_id, product_id) values (127, 'A chic leather crossbody bag for everyday use.', 40, 546, 1808);
insert into Rating (id, review, score, user_id, product_id) values (128, 'Stream HD video wirelessly from devices to TV.', 68, 788, 1379);
insert into Rating (id, review, score, user_id, product_id) values (129, 'Instant noodles with a spicy Thai sauce for quick meals.', 48, 563, 85);
insert into Rating (id, review, score, user_id, product_id) values (130, 'Colorful tapestry to add charm to any room.', 52, 523, 600);
insert into Rating (id, review, score, user_id, product_id) values (131, 'Compact vacuum designed specifically for cleaning vehicles.', 42, 651, 1090);
insert into Rating (id, review, score, user_id, product_id) values (132, 'Official size basketball for indoor and outdoor play.', 67, 118, 1347);
insert into Rating (id, review, score, user_id, product_id) values (133, 'Quick and easy fried rice mixed with vegetables and soy sauce.', 41, 631, 1015);
insert into Rating (id, review, score, user_id, product_id) values (134, 'GPS pet collar that helps locate your pet via smartphone app.', 14, 584, 1706);
insert into Rating (id, review, score, user_id, product_id) values (135, 'Soft hamburger buns made with whole grains.', 63, 540, 1539);
insert into Rating (id, review, score, user_id, product_id) values (136, 'Adjustable lamp with multiple brightness levels and colors.', 13, 68, 1244);
insert into Rating (id, review, score, user_id, product_id) values (137, 'Electric foot massager for relaxation and relief.', 43, 339, 456);
insert into Rating (id, review, score, user_id, product_id) values (138, 'Sweet and nutty filling for delicious homemade pecan pie.', 60, 374, 803);
insert into Rating (id, review, score, user_id, product_id) values (139, 'Comfortable eye mask that includes noise-canceling ear plugs.', 43, 675, 949);
insert into Rating (id, review, score, user_id, product_id) values (140, 'Durable yoga strap for deeper stretches.', 6, 296, 1420);
insert into Rating (id, review, score, user_id, product_id) values (141, 'High-performance compression tights designed for optimal support and comfort.', 69, 456, 775);
insert into Rating (id, review, score, user_id, product_id) values (142, 'Creamy dip made with real onions and spices, great for chips and veggies.', 94, 193, 1419);
insert into Rating (id, review, score, user_id, product_id) values (143, 'Compact hand mixer for easy baking.', 92, 523, 146);
insert into Rating (id, review, score, user_id, product_id) values (144, 'Delicious pie filled with coconut cream and topped with whipped cream.', 5, 745, 821);
insert into Rating (id, review, score, user_id, product_id) values (145, 'Durable cover to protect your grill from the elements.', 66, 470, 593);
insert into Rating (id, review, score, user_id, product_id) values (146, 'A light and tangy dressing with poppy seeds, perfect for salads.', 80, 458, 373);
insert into Rating (id, review, score, user_id, product_id) values (147, 'Waterproof cover to protect car seats from pet hair and dirt.', 49, 672, 1361);
insert into Rating (id, review, score, user_id, product_id) values (148, 'Reusable silicone mats for non-stick baking.', 48, 403, 1190);
insert into Rating (id, review, score, user_id, product_id) values (149, 'A fresh, flavorful basil pesto for pasta and more', 65, 422, 123);
insert into Rating (id, review, score, user_id, product_id) values (150, 'Shredded potatoes, perfect for breakfasts.', 1, 64, 276);
insert into Rating (id, review, score, user_id, product_id) values (151, 'Artisan bread with caraway seeds for added flavor.', 74, 566, 170);
insert into Rating (id, review, score, user_id, product_id) values (152, 'Nutritious protein bar with cherry and almond flavor, great for on-the-go.', 27, 329, 433);
insert into Rating (id, review, score, user_id, product_id) values (153, 'Compact hose reel to keep your garden tidy.', 50, 610, 1704);
insert into Rating (id, review, score, user_id, product_id) values (154, 'Refreshing sparkling water with cucumber and lime flavor.', 77, 267, 1752);
insert into Rating (id, review, score, user_id, product_id) values (155, 'Just add water for a quick pasta sauce.', 73, 300, 1701);
insert into Rating (id, review, score, user_id, product_id) values (156, 'Grilled chicken skewers glazed with teriyaki sauce.', 42, 391, 1970);
insert into Rating (id, review, score, user_id, product_id) values (157, 'High-quality leather wallet with multiple compartments.', 14, 416, 54);
insert into Rating (id, review, score, user_id, product_id) values (158, 'Gourmet potato skins loaded with cheddar cheese and bacon.', 50, 187, 1475);
insert into Rating (id, review, score, user_id, product_id) values (159, 'Rich spaghetti sauce, a perfect pasta sauce.', 78, 490, 882);
insert into Rating (id, review, score, user_id, product_id) values (160, 'Reusable suction cup hooks for hanging items.', 90, 349, 1386);
insert into Rating (id, review, score, user_id, product_id) values (161, 'Everything you need to build a festive gingerbread house.', 94, 669, 539);
insert into Rating (id, review, score, user_id, product_id) values (162, 'Qi-certified charger for fast wireless charging of smartphones.', 73, 476, 314);
insert into Rating (id, review, score, user_id, product_id) values (163, 'Crispy almonds coated with cinnamon and sugar for a sweet and crunchy snack.', 54, 781, 148);
insert into Rating (id, review, score, user_id, product_id) values (164, 'Marinated chicken skewers with lemon and dill flavor, grilled to perfection.', 98, 393, 975);
insert into Rating (id, review, score, user_id, product_id) values (165, 'Stylish and modern holder for storing wine bottles on walls.', 77, 350, 933);
insert into Rating (id, review, score, user_id, product_id) values (166, 'Short-grain sushi rice for perfect rolls.', 70, 525, 648);
insert into Rating (id, review, score, user_id, product_id) values (167, 'A frozen cheesy bake made with cauliflower, great as a side dish or a vegetarian meal.', 51, 169, 1783);
insert into Rating (id, review, score, user_id, product_id) values (168, 'A wholesome granola with bits of apple and a touch of cinnamon.', 73, 564, 962);
insert into Rating (id, review, score, user_id, product_id) values (169, 'Rich spaghetti sauce, a perfect pasta sauce.', 69, 213, 880);
insert into Rating (id, review, score, user_id, product_id) values (170, 'Trendy high-low tee with a relaxed fit, ideal for weekends.', 59, 790, 474);
insert into Rating (id, review, score, user_id, product_id) values (171, 'Creamy mashed potatoes infused with roasted garlic flavor.', 24, 551, 668);
insert into Rating (id, review, score, user_id, product_id) values (172, 'Colorful and child-friendly gardening tools for little hands.', 7, 155, 174);
insert into Rating (id, review, score, user_id, product_id) values (173, 'Ziti pasta baked with marinara and parmesan cheese', 86, 298, 100);
insert into Rating (id, review, score, user_id, product_id) values (174, 'Multifunctional smartwatch for fitness tracking.', 59, 195, 256);
insert into Rating (id, review, score, user_id, product_id) values (175, 'Compact electronic drum kit for musicians of all levels.', 20, 786, 744);
insert into Rating (id, review, score, user_id, product_id) values (176, 'Soft throw blanket for cozy home decor.', 37, 437, 1330);
insert into Rating (id, review, score, user_id, product_id) values (177, 'Essential survival gear kit for emergencies.', 86, 138, 530);
insert into Rating (id, review, score, user_id, product_id) values (178, 'Crispy cheese snacks that melt in your mouth.', 93, 609, 276);
insert into Rating (id, review, score, user_id, product_id) values (179, 'Set of flexible molds for baking cakes and pastries.', 99, 641, 159);
insert into Rating (id, review, score, user_id, product_id) values (180, 'A mix of strawberries, blueberries, and raspberries, perfect for smoothies.', 76, 420, 1080);
insert into Rating (id, review, score, user_id, product_id) values (181, 'Portable battery pack to charge laptops while on the move.', 19, 321, 381);
insert into Rating (id, review, score, user_id, product_id) values (182, 'Comfortable harness designed to keep pets safe in the car.', 5, 585, 515);
insert into Rating (id, review, score, user_id, product_id) values (183, 'Crispy mini pretzels, a great snack any time of day.', 27, 534, 354);
insert into Rating (id, review, score, user_id, product_id) values (184, 'Classic ketchup made from organic tomatoes, no added sugar.', 14, 691, 113);
insert into Rating (id, review, score, user_id, product_id) values (185, 'Essential ingredient for baking and cooking.', 92, 275, 469);
insert into Rating (id, review, score, user_id, product_id) values (186, 'Easy-to-use tiebacks for curtains or drapes.', 18, 195, 1118);
insert into Rating (id, review, score, user_id, product_id) values (187, 'Beautiful wall calendar for organizing your schedule.', 93, 176, 947);
insert into Rating (id, review, score, user_id, product_id) values (188, 'Assorted indoor plants for home decor.', 63, 271, 1630);
insert into Rating (id, review, score, user_id, product_id) values (189, 'Soft and chewy cookies made with creamy peanut butter.', 74, 355, 1933);
insert into Rating (id, review, score, user_id, product_id) values (190, 'Lightweight and portable folding table for camping or picnics.', 24, 369, 598);
insert into Rating (id, review, score, user_id, product_id) values (191, 'Stabilizer for smooth video recording with smartphones.', 16, 570, 1466);
insert into Rating (id, review, score, user_id, product_id) values (192, 'Compact Bluetooth speaker with rich sound quality.', 63, 299, 827);
insert into Rating (id, review, score, user_id, product_id) values (193, 'Wi-Fi enabled plug for controlling devices from your smartphone.', 29, 32, 858);
insert into Rating (id, review, score, user_id, product_id) values (194, 'Chewy granola bars made with honey and almonds.', 19, 69, 655);
insert into Rating (id, review, score, user_id, product_id) values (195, 'Special attachment for vacuum cleaners to remove pet hair easily.', 44, 479, 1021);
insert into Rating (id, review, score, user_id, product_id) values (196, 'Sweet and nutty filling for delicious homemade pecan pie.', 15, 216, 1295);
insert into Rating (id, review, score, user_id, product_id) values (197, 'Delicious cookies made with almond flour for a gluten-free treat.', 99, 28, 1040);
insert into Rating (id, review, score, user_id, product_id) values (198, 'Frozen chicken wings with garlic parmesan sauce.', 84, 584, 548);
insert into Rating (id, review, score, user_id, product_id) values (199, 'Marinated chicken thighs with smoked paprika for a smoky flavor.', 45, 683, 702);
insert into Rating (id, review, score, user_id, product_id) values (200, 'Roasted cashews coated in honey and sesame seeds for a sweet treat.', 24, 131, 1294);
insert into Rating (id, review, score, user_id, product_id) values (201, 'Elegant tea set that includes an infuser for brewing.', 77, 244, 997);
insert into Rating (id, review, score, user_id, product_id) values (202, 'Modern desk lamp that features a built-in USB charging port.', 3, 505, 658);
insert into Rating (id, review, score, user_id, product_id) values (203, 'Crunchy cacao nibs, great for adding to smoothies or baking.', 2, 3, 639);
insert into Rating (id, review, score, user_id, product_id) values (204, 'Frozen stir-fry mix with chicken, veggies, and teriyaki sauce.', 86, 134, 1724);
insert into Rating (id, review, score, user_id, product_id) values (205, 'Fresh salsa made with tomatoes, onions, and cilantro.', 92, 383, 1618);
insert into Rating (id, review, score, user_id, product_id) values (206, 'No-bake energy bites made with peanut butter and oats.', 47, 226, 1154);
insert into Rating (id, review, score, user_id, product_id) values (207, 'Lightweight tennis racket for beginners and advanced players.', 90, 51, 336);
insert into Rating (id, review, score, user_id, product_id) values (208, 'Heavy-duty rope suitable for boating, camping, and general use.', 87, 586, 153);
insert into Rating (id, review, score, user_id, product_id) values (209, 'Set of unique wooden coasters for drinks and decor.', 26, 233, 1832);
insert into Rating (id, review, score, user_id, product_id) values (210, 'Comfortable pet carrier for travel and vet visits.', 95, 534, 465);
insert into Rating (id, review, score, user_id, product_id) values (211, 'Organic rolled oats, great for breakfast or baking.', 15, 629, 851);
insert into Rating (id, review, score, user_id, product_id) values (212, 'Non-stick and heat-resistant utensils for cooking.', 53, 121, 418);
insert into Rating (id, review, score, user_id, product_id) values (213, 'Durable and versatile backpack for outdoor and travel use.', 87, 286, 127);
insert into Rating (id, review, score, user_id, product_id) values (214, 'Lightweight leaf blower for maintaining outdoor spaces.', 93, 265, 68);
insert into Rating (id, review, score, user_id, product_id) values (215, 'Small fridge designed to keep skincare products cool and fresh.', 13, 39, 1945);
insert into Rating (id, review, score, user_id, product_id) values (216, 'Rich chocolate protein powder for smoothies and baking.', 26, 359, 379);
insert into Rating (id, review, score, user_id, product_id) values (217, 'Tangy and crunchy dill pickles.', 16, 548, 111);
insert into Rating (id, review, score, user_id, product_id) values (218, 'A comfortable henley shirt made of soft cotton, perfect for casual outings.', 20, 27, 1092);
insert into Rating (id, review, score, user_id, product_id) values (219, 'A chic leather crossbody bag for everyday use.', 83, 408, 1439);
insert into Rating (id, review, score, user_id, product_id) values (220, 'Assorted fruit-flavored gummy snacks that kids love.', 86, 466, 774);
insert into Rating (id, review, score, user_id, product_id) values (221, 'Safe and fun trampoline for children.', 81, 665, 353);
insert into Rating (id, review, score, user_id, product_id) values (222, 'Easy-to-make falafel mix for a tasty vegetarian meal.', 49, 24, 899);
insert into Rating (id, review, score, user_id, product_id) values (223, 'A flavorful blend of rice with tropical pineapple and coconut flavors.', 10, 641, 817);
insert into Rating (id, review, score, user_id, product_id) values (224, 'Retro instant camera for capturing and printing photos instantly.', 86, 200, 392);
insert into Rating (id, review, score, user_id, product_id) values (225, 'Digital scale to avoid overweight baggage fees.', 48, 290, 1316);
insert into Rating (id, review, score, user_id, product_id) values (226, 'Individually packaged bars made with dried fruits and nuts.', 71, 6, 310);
insert into Rating (id, review, score, user_id, product_id) values (227, 'A ready-to-eat salad made with chickpeas and veggies.', 40, 100, 1017);
insert into Rating (id, review, score, user_id, product_id) values (228, 'Portable solar shower for camping and outdoor use.', 43, 141, 1617);
insert into Rating (id, review, score, user_id, product_id) values (229, 'Refreshing green tea infused with peach, perfect for a hot day.', 55, 358, 462);
insert into Rating (id, review, score, user_id, product_id) values (230, 'Stream HD video wirelessly from devices to TV.', 33, 105, 1360);
insert into Rating (id, review, score, user_id, product_id) values (231, 'A soothing herbal tea made from ginger root.', 30, 215, 1280);
insert into Rating (id, review, score, user_id, product_id) values (232, 'Ready-to-eat beet salad with dressing, great side dish.', 29, 353, 1701);
insert into Rating (id, review, score, user_id, product_id) values (233, 'Popcorn tossed with sweet or savory flavors for a tasty snack.', 69, 280, 1323);
insert into Rating (id, review, score, user_id, product_id) values (234, 'Notepad made from recycled paper for sustainable note-taking.', 92, 211, 1049);
insert into Rating (id, review, score, user_id, product_id) values (235, 'Perfectly balanced sweet and tangy BBQ sauce for dipping or grilling.', 62, 171, 1662);
insert into Rating (id, review, score, user_id, product_id) values (236, 'Foldable chair equipped with a cooler pouch.', 83, 479, 930);
insert into Rating (id, review, score, user_id, product_id) values (237, 'Cozy oversized sweater perfect for chilly days with a textured knit design.', 83, 652, 1430);
insert into Rating (id, review, score, user_id, product_id) values (238, 'Snooze function and LED display for easy reading.', 82, 722, 909);
insert into Rating (id, review, score, user_id, product_id) values (239, 'Digital scale for precise cooking measurements.', 72, 586, 453);
insert into Rating (id, review, score, user_id, product_id) values (240, 'Large electric griddle for family meals.', 76, 536, 674);
insert into Rating (id, review, score, user_id, product_id) values (241, 'Durable speaker designed for outdoor use with water resistance.', 94, 82, 1369);
insert into Rating (id, review, score, user_id, product_id) values (242, 'Comprehensive tool set for gardening enthusiasts.', 66, 728, 752);
insert into Rating (id, review, score, user_id, product_id) values (243, 'A hearty soup made with lentils, coconut milk, and a blend of spices for a tropical flavor.', 84, 649, 752);
insert into Rating (id, review, score, user_id, product_id) values (244, 'Classic wooden puzzle game for kids and adults.', 45, 251, 522);
insert into Rating (id, review, score, user_id, product_id) values (245, 'Love-themed molds for creating desserts and treats.', 69, 606, 126);
insert into Rating (id, review, score, user_id, product_id) values (246, 'Freshly baked whole wheat bread, rich in fiber.', 30, 292, 108);
insert into Rating (id, review, score, user_id, product_id) values (247, 'Double-sided art easel for painting and drawing.', 82, 317, 287);
insert into Rating (id, review, score, user_id, product_id) values (248, 'Clip-on guitar tuner with LCD display.', 28, 149, 177);
insert into Rating (id, review, score, user_id, product_id) values (249, 'A sleek leather wallet that combines style and functionality.', 68, 403, 1395);
insert into Rating (id, review, score, user_id, product_id) values (250, 'Crunchy pretzel sticks made with honey and whole wheat.', 86, 564, 332);
insert into Rating (id, review, score, user_id, product_id) values (251, 'Frozen shrimp seasoned with chili and lime, perfect for quick dinners.', 31, 609, 503);
insert into Rating (id, review, score, user_id, product_id) values (252, 'Lightweight and durable hammock for relaxing in nature.', 26, 759, 1407);
insert into Rating (id, review, score, user_id, product_id) values (253, 'Stylish insulated lunch bag for on-the-go meals.', 37, 637, 11);
insert into Rating (id, review, score, user_id, product_id) values (254, 'Easy setup tent perfect for camping and outdoor festivals.', 85, 699, 427);
insert into Rating (id, review, score, user_id, product_id) values (255, 'Oven-roasted potatoes tossed in garlic and parmesan cheese seasoning.', 74, 464, 1835);
insert into Rating (id, review, score, user_id, product_id) values (256, 'Creamy macaroni and cheese baked to perfection.', 22, 370, 1727);
insert into Rating (id, review, score, user_id, product_id) values (257, 'Fresh mango salsa with a hint of lime for a zesty topping.', 54, 121, 203);
insert into Rating (id, review, score, user_id, product_id) values (258, 'Portable folding table for outdoor events.', 100, 648, 2);
insert into Rating (id, review, score, user_id, product_id) values (259, 'Portable case to organize and protect jewelry on trips.', 26, 396, 165);
insert into Rating (id, review, score, user_id, product_id) values (260, 'A stylish midi dress with stylish pleats, suitable for any occasion.', 99, 156, 1371);
insert into Rating (id, review, score, user_id, product_id) values (261, 'Rechargeable electric wine opener for effortless uncorking.', 72, 82, 491);
insert into Rating (id, review, score, user_id, product_id) values (262, 'Comfortable hiking boots for outdoor adventures.', 4, 353, 1727);
insert into Rating (id, review, score, user_id, product_id) values (263, 'A wholesome granola with bits of apple and a touch of cinnamon.', 81, 576, 449);
insert into Rating (id, review, score, user_id, product_id) values (264, 'Comfortable carry for pets while hiking or traveling.', 31, 535, 1526);
insert into Rating (id, review, score, user_id, product_id) values (265, 'Filters allergens and pollutants from the air for a healthier home.', 26, 104, 1385);
insert into Rating (id, review, score, user_id, product_id) values (266, 'Sturdy grip to hold your phone securely while taking selfies.', 23, 118, 1830);
insert into Rating (id, review, score, user_id, product_id) values (267, 'Unsweetened coconut flakes for baking and topping.', 85, 373, 1834);
insert into Rating (id, review, score, user_id, product_id) values (268, 'Creamy ice cream with refreshing mint flavor and chocolate chips.', 58, 264, 1378);
insert into Rating (id, review, score, user_id, product_id) values (269, 'Fun fridge magnets to decorate your kitchen.', 22, 160, 683);
insert into Rating (id, review, score, user_id, product_id) values (270, 'Personalized wooden puzzles for children that encourage learning.', 62, 167, 1544);
insert into Rating (id, review, score, user_id, product_id) values (271, 'Use this foam roller for effective post-workout recovery.', 99, 766, 674);
insert into Rating (id, review, score, user_id, product_id) values (272, 'Set of decorative pillow covers to enhance your home decor.', 99, 293, 1277);
insert into Rating (id, review, score, user_id, product_id) values (273, 'Monitor and interact with your pet remotely with this camera.', 76, 675, 291);
insert into Rating (id, review, score, user_id, product_id) values (274, 'Rich and creamy Caesar dressing for salads and wraps.', 49, 503, 1416);
insert into Rating (id, review, score, user_id, product_id) values (275, 'Multi-functional tool for emergency situations in the car.', 60, 194, 1796);
insert into Rating (id, review, score, user_id, product_id) values (276, 'Durable tarp for outdoor camping and protection.', 52, 724, 988);
insert into Rating (id, review, score, user_id, product_id) values (277, 'A smoky blend of spices for grilling and roasting.', 75, 634, 1944);
insert into Rating (id, review, score, user_id, product_id) values (278, 'No-bake energy balls made with oats, chocolate chips, and honey.', 4, 66, 799);
insert into Rating (id, review, score, user_id, product_id) values (279, 'Digital scale to avoid overweight baggage fees.', 74, 16, 635);
insert into Rating (id, review, score, user_id, product_id) values (280, 'Crunchy granola with pumpkin spice flavor.', 82, 575, 1158);
insert into Rating (id, review, score, user_id, product_id) values (281, 'Compact hair straightener for travel.', 43, 78, 1720);
insert into Rating (id, review, score, user_id, product_id) values (282, 'Ideal for creating custom designs on t-shirts and fabrics.', 60, 596, 1197);
insert into Rating (id, review, score, user_id, product_id) values (283, 'Refreshing basil-infused lemonade for a cool drink.', 54, 50, 354);
insert into Rating (id, review, score, user_id, product_id) values (284, 'Soft and delicious garlic-infused flatbread, perfect for dipping.', 19, 362, 1072);
insert into Rating (id, review, score, user_id, product_id) values (285, 'Easy-to-read digital kitchen timer with alarms.', 97, 88, 1587);
insert into Rating (id, review, score, user_id, product_id) values (286, 'Portable water bottle for pets when traveling.', 75, 274, 508);
insert into Rating (id, review, score, user_id, product_id) values (287, 'Eco-friendly solar lights for pathways and gardens.', 58, 747, 1050);
insert into Rating (id, review, score, user_id, product_id) values (288, 'Grilled chicken skewers glazed with teriyaki sauce.', 72, 453, 702);
insert into Rating (id, review, score, user_id, product_id) values (289, 'Ergonomic stand for laptops to improve posture while working.', 24, 507, 1164);
insert into Rating (id, review, score, user_id, product_id) values (290, 'A mix of fresh raspberries, blueberries, and blackberries.', 16, 248, 1561);
insert into Rating (id, review, score, user_id, product_id) values (291, 'Functional leggings designed for maximum comfort during workouts.', 20, 495, 1601);
insert into Rating (id, review, score, user_id, product_id) values (292, 'Fast and convenient air pump for inflating toys and furniture.', 52, 583, 1595);
insert into Rating (id, review, score, user_id, product_id) values (293, 'Timeless black trousers for a smart and sophisticated look.', 5, 783, 602);
insert into Rating (id, review, score, user_id, product_id) values (294, 'Spicy and creamy dip made with shredded chicken, perfect for parties.', 52, 371, 1367);
insert into Rating (id, review, score, user_id, product_id) values (295, 'Pitted black olives, perfect for salads and pizzas.', 18, 761, 1963);
insert into Rating (id, review, score, user_id, product_id) values (296, 'Roasted almonds dipped in rich dark chocolate.', 38, 469, 124);
insert into Rating (id, review, score, user_id, product_id) values (297, 'Beginner-friendly acoustic guitar with natural finish.', 27, 736, 911);
insert into Rating (id, review, score, user_id, product_id) values (298, 'Insulated pitcher to keep beverages cold or hot.', 48, 401, 1191);
insert into Rating (id, review, score, user_id, product_id) values (299, 'A soothing herbal tea made from ginger root.', 60, 463, 2);
insert into Rating (id, review, score, user_id, product_id) values (300, 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.', 49, 167, 1661);
insert into Rating (id, review, score, user_id, product_id) values (301, 'Prevent water damage with drip trays for potted plants.', 83, 778, 604);
insert into Rating (id, review, score, user_id, product_id) values (302, 'Stability ball for Pilates and yoga workouts.', 51, 306, 1359);
insert into Rating (id, review, score, user_id, product_id) values (303, 'A light and breezy top ideal for warm days.', 40, 294, 1543);
insert into Rating (id, review, score, user_id, product_id) values (304, 'High-performance compression tights designed for optimal support and comfort.', 38, 462, 1196);
insert into Rating (id, review, score, user_id, product_id) values (305, 'A selection of different flavored hummus, great for snacking.', 88, 511, 1127);
insert into Rating (id, review, score, user_id, product_id) values (306, 'Refreshing sparkling water with lemon and lime flavor', 81, 219, 1795);
insert into Rating (id, review, score, user_id, product_id) values (307, 'GPS collar that monitors your pet''s location and activity level.', 80, 333, 566);
insert into Rating (id, review, score, user_id, product_id) values (308, 'Gentle brush for removing loose fur from pets.', 20, 553, 782);
insert into Rating (id, review, score, user_id, product_id) values (309, 'Marinated grilled chicken breasts seasoned with garlic and herbs.', 29, 435, 812);
insert into Rating (id, review, score, user_id, product_id) values (310, 'Creamy ice cream with a warm cinnamon flavor, perfect for dessert.', 34, 229, 1746);
insert into Rating (id, review, score, user_id, product_id) values (311, 'Savory sauce for vegetable and meat stir-fries.', 94, 634, 1616);
insert into Rating (id, review, score, user_id, product_id) values (312, 'Floating bookshelf to display your favorite books.', 25, 42, 458);
insert into Rating (id, review, score, user_id, product_id) values (313, 'Elegant glass teapot for brewing loose tea.', 25, 667, 1681);
insert into Rating (id, review, score, user_id, product_id) values (314, 'A stylish midi dress with stylish pleats, suitable for any occasion.', 70, 413, 1830);
insert into Rating (id, review, score, user_id, product_id) values (315, 'Easy-to-install lights to brighten kitchen cabinets and workspaces.', 44, 602, 1131);
insert into Rating (id, review, score, user_id, product_id) values (316, 'Spicy jalapenos stuffed with cheese, ideal for appetizers.', 53, 103, 570);
insert into Rating (id, review, score, user_id, product_id) values (317, 'A comfortable sweatshirt featuring a bold graphic print.', 98, 752, 1677);
insert into Rating (id, review, score, user_id, product_id) values (318, 'Natural pink salt, perfect for seasoning.', 71, 792, 510);
insert into Rating (id, review, score, user_id, product_id) values (319, 'Fresh cabbage and carrot slaw mix for salads.', 100, 483, 638);
insert into Rating (id, review, score, user_id, product_id) values (320, 'Lightweight backpack with an insulated water reservoir for hydration on the go.', 43, 182, 150);
insert into Rating (id, review, score, user_id, product_id) values (321, 'Mixed fresh vegetables for stir-frying or roasting.', 1, 378, 1744);
insert into Rating (id, review, score, user_id, product_id) values (322, 'A nutrient-packed salad mix with kale, quinoa, and a lemon vinaigrette, ready to eat.', 17, 588, 978);
insert into Rating (id, review, score, user_id, product_id) values (323, 'Baking mix to create your favorite Samoa-style cookies at home.', 100, 785, 1755);
insert into Rating (id, review, score, user_id, product_id) values (324, 'Fluffy quinoa mixed with lemon zest and herbs, a perfect side.', 75, 338, 639);
insert into Rating (id, review, score, user_id, product_id) values (325, 'Frozen cauliflower rice blended with mixed vegetables and seasonings.', 7, 715, 1273);
insert into Rating (id, review, score, user_id, product_id) values (326, 'Crunchy and nutritious almonds, perfect for snacking.', 61, 774, 586);
insert into Rating (id, review, score, user_id, product_id) values (327, 'Adjustable stand for portable speakers and devices.', 80, 582, 1920);
insert into Rating (id, review, score, user_id, product_id) values (328, 'Microwaveable heating pad for muscle pain relief and relaxation.', 68, 289, 437);
insert into Rating (id, review, score, user_id, product_id) values (329, 'Energy-efficient lights that charge during the day and illuminate at night.', 89, 690, 461);
insert into Rating (id, review, score, user_id, product_id) values (330, 'A warm and sustainable wool scarf for chilly days.', 11, 86, 985);
insert into Rating (id, review, score, user_id, product_id) values (331, 'All-in-one kit for growing herbs in your kitchen.', 78, 509, 1138);
insert into Rating (id, review, score, user_id, product_id) values (332, 'Classic wooden puzzle game for kids and adults.', 21, 391, 1945);
insert into Rating (id, review, score, user_id, product_id) values (333, 'Everything you need to make your own scented candles at home.', 40, 212, 1230);
insert into Rating (id, review, score, user_id, product_id) values (334, 'Fresh and juicy cherry tomatoes for salads and snacking.', 58, 760, 1528);
insert into Rating (id, review, score, user_id, product_id) values (335, 'Multi-function pressure cooker that can sauté, steam, and slow cook.', 99, 297, 1190);
insert into Rating (id, review, score, user_id, product_id) values (336, 'Fine granulated sugar for all your baking needs.', 87, 554, 1910);
insert into Rating (id, review, score, user_id, product_id) values (337, 'Energy-efficient lights to illuminate outdoor areas.', 75, 581, 1008);
insert into Rating (id, review, score, user_id, product_id) values (338, 'Eco-friendly electric bike with a 30-mile range.', 40, 180, 1960);
insert into Rating (id, review, score, user_id, product_id) values (339, 'Classic cereal made with whole grains and honey.', 91, 299, 677);
insert into Rating (id, review, score, user_id, product_id) values (340, 'Travel-friendly dog bowl that is collapsible for easy storage.', 92, 266, 1654);
insert into Rating (id, review, score, user_id, product_id) values (341, 'Soft and breathable cotton sweatpants perfect for lounging or workouts.', 65, 451, 353);
insert into Rating (id, review, score, user_id, product_id) values (342, 'Comfortable and reusable face masks in different styles.', 97, 468, 1977);
insert into Rating (id, review, score, user_id, product_id) values (343, 'Hearty minestrone soup loaded with vegetables and pasta.', 44, 572, 444);
insert into Rating (id, review, score, user_id, product_id) values (344, 'A simple, no-bake cheesecake mix to create your own delicious cheesecake.', 73, 60, 1112);
insert into Rating (id, review, score, user_id, product_id) values (345, 'Quick-cooking couscous flavored with herbs and spices.', 1, 430, 661);
insert into Rating (id, review, score, user_id, product_id) values (346, 'Hands-free waist pack for carrying essentials while walking your dog.', 65, 421, 1877);
insert into Rating (id, review, score, user_id, product_id) values (347, 'Crunchy croutons with a blend of herbs for salads.', 19, 254, 1647);
insert into Rating (id, review, score, user_id, product_id) values (348, 'Multifunctional smartwatch for fitness tracking.', 68, 713, 107);
insert into Rating (id, review, score, user_id, product_id) values (349, 'Sliced black olives, perfect for salads and pizzas.', 90, 542, 318);
insert into Rating (id, review, score, user_id, product_id) values (350, 'Creamy mashed sweet potatoes, ready to heat and serve.', 84, 88, 1952);
insert into Rating (id, review, score, user_id, product_id) values (351, 'A delicious tart filled with fresh raspberry filling.', 86, 157, 980);
insert into Rating (id, review, score, user_id, product_id) values (352, 'Lightweight cover-up perfect for the beach, with a breezy design.', 49, 672, 306);
insert into Rating (id, review, score, user_id, product_id) values (353, 'Crunchy corn chips flavored with chili and lime for a zesty kick.', 28, 659, 726);
insert into Rating (id, review, score, user_id, product_id) values (354, 'Rich cream extracted from coconut milk, ideal for desserts.', 53, 344, 1941);
insert into Rating (id, review, score, user_id, product_id) values (355, 'Natural honey sourced from wildflowers.', 16, 532, 1121);
insert into Rating (id, review, score, user_id, product_id) values (356, 'Stylish ankle strap heels for a classy look at any event.', 42, 735, 1950);
insert into Rating (id, review, score, user_id, product_id) values (357, 'Frozen onion rings, crispy and ready to bake.', 71, 411, 1765);
insert into Rating (id, review, score, user_id, product_id) values (358, 'Space-saving solution to store shoes and keep them organized.', 88, 36, 1098);
insert into Rating (id, review, score, user_id, product_id) values (359, 'Water bottle that tracks your hydration levels.', 80, 521, 1216);
insert into Rating (id, review, score, user_id, product_id) values (360, 'Sweet mixture of cinnamon and sugar for sprinkling.', 75, 229, 1967);
insert into Rating (id, review, score, user_id, product_id) values (361, 'Crispy and chewy granola bars, perfect for on-the-go.', 27, 326, 537);
insert into Rating (id, review, score, user_id, product_id) values (362, 'Make delicious waffles with this user-friendly device.', 62, 735, 906);
insert into Rating (id, review, score, user_id, product_id) values (363, 'A flavorful garlic butter blend, perfect for cooking or baking.', 78, 37, 495);
insert into Rating (id, review, score, user_id, product_id) values (364, 'Classic fit blue jeans with a slight stretch for comfort and durability.', 40, 118, 1153);
insert into Rating (id, review, score, user_id, product_id) values (365, 'Easy-to-make falafel mix for a tasty vegetarian meal.', 29, 455, 1668);
insert into Rating (id, review, score, user_id, product_id) values (366, 'Compact hand mixer for easy baking.', 4, 166, 276);
insert into Rating (id, review, score, user_id, product_id) values (367, 'Comfortable pillow with built-in massage features.', 32, 543, 277);
insert into Rating (id, review, score, user_id, product_id) values (368, 'Savory quiche loaded with spinach and cheese.', 40, 664, 711);
insert into Rating (id, review, score, user_id, product_id) values (369, 'Shredded potatoes, perfect for breakfasts.', 13, 38, 1968);
insert into Rating (id, review, score, user_id, product_id) values (370, 'A comfortable henley shirt made of soft cotton, perfect for casual outings.', 70, 289, 1964);
insert into Rating (id, review, score, user_id, product_id) values (371, 'Crunchy pretzels coated in rich chocolate, a sweet treat.', 55, 568, 1763);
insert into Rating (id, review, score, user_id, product_id) values (372, 'Stylish scarves to accessorize any outfit.', 34, 746, 1362);
insert into Rating (id, review, score, user_id, product_id) values (373, 'A flavorful rice side dish seasoned with herbs and spices.', 24, 331, 1568);
insert into Rating (id, review, score, user_id, product_id) values (374, 'A blend of herbs and garlic for seasoning meats and vegetables.', 12, 115, 805);
insert into Rating (id, review, score, user_id, product_id) values (375, 'Safe and fun trampoline for children.', 48, 153, 1324);
insert into Rating (id, review, score, user_id, product_id) values (376, 'Delicious cookies with cranberries and almonds in every bite.', 59, 601, 171);
insert into Rating (id, review, score, user_id, product_id) values (377, 'Monthly subscription for freshly roasted coffee delivered to your door.', 44, 63, 826);
insert into Rating (id, review, score, user_id, product_id) values (378, 'Crunchy croutons with a blend of herbs for salads.', 2, 156, 1664);
insert into Rating (id, review, score, user_id, product_id) values (379, 'Shredded cabbage and carrots for coleslaw.', 35, 131, 689);
insert into Rating (id, review, score, user_id, product_id) values (380, 'Instant-read thermometer for precise cooking temperatures.', 93, 669, 1108);
insert into Rating (id, review, score, user_id, product_id) values (381, 'Canned diced tomatoes, great base for sauces and soups.', 58, 654, 41);
insert into Rating (id, review, score, user_id, product_id) values (382, 'Quick oatmeal with various flavors', 57, 311, 251);
insert into Rating (id, review, score, user_id, product_id) values (383, 'Adjustable window blinds for privacy and light control.', 14, 755, 276);
insert into Rating (id, review, score, user_id, product_id) values (384, 'Individually packaged bars made with dried fruits and nuts.', 75, 367, 1138);
insert into Rating (id, review, score, user_id, product_id) values (385, 'Bold graphic hoodie featuring a comfortable fit and soft fabric.', 46, 764, 702);
insert into Rating (id, review, score, user_id, product_id) values (386, 'Frozen shrimp sautéed in garlic butter, ready to thaw and serve over pasta or rice.', 76, 790, 1558);
insert into Rating (id, review, score, user_id, product_id) values (387, 'Complete set for mixing cocktails at home.', 38, 163, 984);
insert into Rating (id, review, score, user_id, product_id) values (388, 'Accurate stopwatch for timing events and workouts.', 51, 161, 170);
insert into Rating (id, review, score, user_id, product_id) values (389, 'Ziti pasta baked with marinara and parmesan cheese', 41, 200, 1483);
insert into Rating (id, review, score, user_id, product_id) values (390, 'Foldable table for working with laptops anywhere.', 42, 342, 691);
insert into Rating (id, review, score, user_id, product_id) values (391, 'Set of decorative ceramic planters for indoor plants.', 83, 712, 1025);
insert into Rating (id, review, score, user_id, product_id) values (392, 'Complete kit to make your own flavored lip balms at home.', 21, 549, 785);
insert into Rating (id, review, score, user_id, product_id) values (393, 'UV light sanitizer for phones and small items.', 13, 733, 10);
insert into Rating (id, review, score, user_id, product_id) values (394, 'Lightweight and portable folding table for camping or picnics.', 34, 154, 482);
insert into Rating (id, review, score, user_id, product_id) values (395, 'Delicious and tangy marinade for grilling or baking chicken.', 55, 541, 1244);
insert into Rating (id, review, score, user_id, product_id) values (396, 'Soft buns perfect for stuffing with your favorite hot dogs.', 52, 502, 1344);
insert into Rating (id, review, score, user_id, product_id) values (397, 'Precision digital scale for accurate cooking measurements.', 44, 249, 396);
insert into Rating (id, review, score, user_id, product_id) values (398, 'Frozen vegan tacos filled with plant-based protein and spices.', 72, 197, 569);
insert into Rating (id, review, score, user_id, product_id) values (399, 'Heavy-duty grill pan for indoor grilling.', 61, 780, 400);
insert into Rating (id, review, score, user_id, product_id) values (400, 'Refreshing tea with honey and lemon flavor, perfect for a warm drink.', 97, 132, 1456);
